### ISSUE TITLE
bkstorages 在 django 3.2.13 版本使用异常

### ISSUE THREAD

**Issue by hanshuaikang** [TencentBlueKing/bkpaas-python-sdk#154]
背景信息:

django 3.2.13 版本, django 默认的Storage 新增了 validate_file_name 方法，该 方法默认接收一个相对路径：
![image](https://github.com/TencentBlueKing/bkpaas-python-sdk/assets/33194175/bc8b88f2-3afc-49da-b734-c0d4473cf852)

![image](https://github.com/TencentBlueKing/bkpaas-python-sdk/assets/33194175/006e0862-e5c3-4c9c-8249-10363145406a)

在最新的 FileSystemStorage 实现中, _save 方法接收一个绝对路径，但是会将路径转换成相对路径，保证下一步的 validate_file_name 不出错：
![image](https://github.com/TencentBlueKing/bkpaas-python-sdk/assets/33194175/b9093060-65d4-44de-8b68-1f37483f6c77)

![image](https://github.com/TencentBlueKing/bkpaas-python-sdk/assets/33194175/c2914728-e099-4f76-9e5e-19384bc84644)

```python
paht = "/app/xxxx"
经过_save() 处理之后 会变为 app/xxxx
````

bkstorages 使用制品库时使用 `BKRepoStorage` 实例。该实例的 _save() 方法并未将绝对路径转化为相对路径的操作。

![image](https://github.com/TencentBlueKing/bkpaas-python-sdk/assets/33194175/f96733b5-8e88-4bfb-8367-047b92ffdf20)

于是就会引发异常:

![image](https://github.com/TencentBlueKing/bkpaas-python-sdk/assets/33194175/277f2120-d943-4846-8d7f-4d2eb72c8c40)

**Comment by piglei** [comment]
经排查，问题原因是使用了低版本的 bkstroages，其使用 urljoin 而不是后来的 safe_join 来拼接最终的文件 key。升级到新版可解决。ref:  [c1b3d4f508b20d4498f788a9cf970d2f9bc674d9](https://github.com/TencentBlueKing/bkpaas-python-sdk/commit/c1b3d4f508b20d4498f788a9cf970d2f9bc674d9)
