### ISSUE TITLE
StructuredEnum with str or int Mixin Breaking Change in Python 3.11

### ISSUE THREAD

**Issue by narasux** [TencentBlueKing/bkpaas-python-sdk#190]
目前业务代码中使用 `blue_krill.data_types.enum.StructuredEnum` 的枚举类，大量使用 int, str 作为 mixin，
以便在编写业务逻辑时，无需使用 `.value` 即可进行比较，字符串格式化（format / f-string），例子如下：

```python
class StoreType(str, StructuredEnum):
    S3 = EnumField("s3")
    BKREPO = EnumField("bkrepo")

class PluginRole(int, StructuredEnum):
    ADMINISTRATOR = EnumField(2)
    DEVELOPER = EnumField(3)
```

但是在 Python 3.11 中，基础 Enum 的 __str__() 行为发生了变化，例如：

```python
from enum import Enum


class Foo(str, Enum):
    BAR = "bar"

# Python 3.10
f"{Foo.BAR}"  # > bar

# Python 3.11
f"{Foo.BAR}"  # > Foo.BAR
```

由于 blue_krill 需要兼容存量的非 3.11+ 的项目，不能直接替换基础的 OrigEnum，需要评估如何处理

相关链接：
- https://github.com/python/cpython/issues/100458
- https://github.com/mobilityhouse/ocpp/issues/447

**Comment by piglei** [comment]
遵循 3.11 中内置 enum 模块的使用标准，并参考其实现，提供 StrStructuredEnum / IntStructuredEnum 两个类，行为类似内置模块的 StrEnum 和 IntEnum 怎么样？

ref:

- https://docs.python.org/3/library/enum.html#enum.StrEnum
- https://docs.python.org/3/library/enum.html#enum.IntEnum
