### ISSUE TITLE
apigw-manager 支持 Django 3.x 版本

### ISSUE THREAD

**Issue by MrLYC** [TencentBlueKing/bkpaas-python-sdk#25]
![image](https://user-images.githubusercontent.com/6391488/150249516-26573dd0-dc75-4dea-9de3-496af5c634d0.png)

**Comment by piglei** [comment]
@MrLYC 补充下更详细的 Issue 说明。

**Comment by MrLYC** [comment]
> Full Python path to the application, e.g. `'django.contrib.admin'`.
>
> This attribute defines which application the configuration applies to. It must be set in all [`[AppConfig](https://docs.djangoproject.com/en/2.2/ref/applications/#django.apps.AppConfig)`](https://docs.djangoproject.com/en/2.2/ref/applications/#django.apps.AppConfig) subclasses.
>
> It must be unique across a Django project.

AppConfig.name 必须为完整导入路径，否则在 Django 3.X 以上版本会报错
