### ISSUE TITLE
关于 blue_krill安装出现哈希值不匹配问题 

### ISSUE THREAD

**Issue by Bugbighuang** [TencentBlueKing/bkpaas-python-sdk#87]
安装 blue_krill出现哈希如下：

Retrieved digest for link blue_krill-1.2.2-py3-none-any.whl(md5:c276504dade988f42f6d0fed21c608b8) not in poetry.lock metadata ['sha256:45a581dfbc3e2d9ee21928cd5e5538e3abad382176800105aee3ccf0f03b7aee', 'sha256:20dac3eed94866cffb4c1771a1eae7ab0f7ed4b877c90d931fb7fc36be8f6c03']

<img width="1889" alt="image" src="https://user-images.githubusercontent.com/49664853/197489626-6f57fc01-56dc-432c-a0a9-f91cf614d09e.png">

**Comment by piglei** [comment]
你好，请提供一下能复现问题的相关信息，比如 poetry 版本、pyproject.toml 文件内容等。

**Comment by Bugbighuang** [comment]
使用版本: Poetry (version 1.2.2)

使用命令： poetry install --sync
poetry add blue-krill=1.2.2 的时候报错哈希值不匹配问题
<img width="436" alt="image" src="https://user-images.githubusercontent.com/49664853/198243754-20835bce-29f8-4733-a938-19c2b720b097.png">

**Comment by Bugbighuang** [comment]
先行修改 poetry 版本问题，切换到 1.1.15 再尝试一遍

**Comment by piglei** [comment]
Poetry 1.2.X 引入了一个问题：https://github.com/python-poetry/poetry/issues/6301 ，导致无法安装从那些仅支持 MD5 digest 的私有 PyPI 源上装包。如果你所在的网络环境，会将 blue-krill 包劫持到某个私有的 pypi 源中（我所在的网络环境就是），就会遇到这个问题。

临时的解决办法：

- 降级 poetry 版本
- 使用一个不劫持 blue-krill 包到私有 PyPI server 的镜像站
